#!/usr/bin/env python

import os
import sys

sys.argv[0] = "Xcalibuds"

if len(sys.argv) == 1:
    # no args ? -> I add "-?" to show defined instances.
    sys.argv.append("-?")

execfile("/users/blissadm/server/src/Xcalibuds.py")

